<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Skill;

class SkillsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $skills = [
            'PHP',
            'Laravel',
            'JavaScript',
            'HTML5',
            'CSS3',
            'JQuery',
            'Python',
            'Vue.js',
            'React.js',
            'Angular',
            'Node.js',
            'Ruby',
            'Ruby on Rails',
            'Java',
            'Spring Boot',
            'C#',
            '.NET Core',
            'ASP.NET',
            'Go',
            'Rust',
            'Kotlin',
            'Swift',
            'Objective-C',
            'SQL',
            'MySQL',
            'PostgreSQL',
            'MongoDB',
            'Firebase',
            'SQLite',
            'GraphQL',
            'REST APIs',
            'Docker',
            'Kubernetes',
            'AWS',
            'Azure',
            'Google Cloud',
            'CI/CD',
            'DevOps',
            'Terraform',
            'Ansible',
            'Linux',
            'Unix',
            'Bash',
            'PowerShell',
            'Git',
            'GitHub',
            'GitLab',
            'Bitbucket',
            'Jenkins',
            'CircleCI',
            'Travis CI',
            'JIRA',
            'Agile',
            'Scrum',
            'Project Management',
            'Machine Learning',
            'Data Science',
            'Data Analysis',
            'Data Visualization',
            'TensorFlow',
            'PyTorch',
            'Numpy',
            'Pandas',
            'Matplotlib',
            'Django',
            'Flask',
            'FastAPI',
            'Symfony',
            'CakePHP',
            'CodeIgniter',
            'Express.js',
            'NestJS',
            'Svelte',
            'Next.js',
            'Nuxt.js',
            'Bootstrap',
            'Tailwind CSS',
            'Material-UI',
            'Ant Design',
            'WebSockets',
            'WebRTC',
            'Microservices',
            'Graph Databases',
            'Neo4j',
            'Blockchain',
            'Solidity',
            'Smart Contracts',
            'Redis',
            'Elasticsearch',
            'RabbitMQ',
            'Kafka',
            'Web Development',
            'Mobile Development',
            'iOS Development',
            'Android Development',
            'Game Development',
            'Unity',
            'Unreal Engine',
            'WebGL',
            'Three.js',
            'D3.js',
            'TypeScript',
            'SCSS',
            'SASS',
            'LESS',
            'WebPack',
            'Gulp',
            'Babel'
        ];

        foreach ($skills as $skill) {
            Skill::create(['name' => $skill]);
        }
    }
}
